version: "3.8"
services:
  database:
    image: postgres:16.2
    environment:
      POSTGRES_USER: kbdb
      POSTGRES_PASSWORD: kbpwd
      POSTGRES_DB: kbdb
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  service:
    image: localhost/kbservice:0.1.0
    environment:
      KB_WEB_SERVER_PORT: 3030
      KB_DB_NAME: kbdb
      KB_DB_USER: kbdb
      KB_DB_PWD: kbpwd
      KB_DB_HOST: database
      KB_DB_PORT: 5432
      RUST_LOG: debug
    ports:
      - 3030:3030
    depends_on:
      - database

volumes:
  postgres:
