version: "3.8"
services:
  database:
    image: postgres:16.2
    environment:
      POSTGRES_USER: kb_user
      POSTGRES_PASSWORD: kb_pwd
      POSTGRES_DB: knowledgebase
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres:
