version: "3.8"
services:
  database:
    image: postgres:16.2
    environment:
      POSTGRES_USER: kbdb
      POSTGRES_PASSWORD: kbpwd
      POSTGRES_DB: kbdb
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres:
