-- Add up migration script here
CREATE TABLE IF NOT EXISTS CATEGORIES (
    CATEGORY_NAME VARCHAR(64) NOT NULL PRIMARY KEY,
    CATEGORY_DESC VARCHAR(256) NOT NULL,
    CREATED_ON TIMESTAMP NOT NULL DEFAULT NOW()
);